# Directories

SAVED_MODEL_DIRECTORY = 'apps/recommend/system'
SAVED_DATASET_DIRECTORY = SAVED_MODEL_DIRECTORY
SAVED_INTERACTIONS_DIRECTORY = SAVED_MODEL_DIRECTORY
SAVED_ITEM_SIMILARITY_MATRIX_DIRECTORY = SAVED_MODEL_DIRECTORY
